### ISSUE TITLE
CONTRIBUTORS Info

### ISSUE THREAD

**Issue by LinguList** [lexibank/oskolskayatungusic#5]
What we are lacking still is the filled out CONTRIBUTORS.md. Here, we have specifically the authors who should get the role Author and @SimonGreenhill for the Lexibankification and myself for the orthoprofile.

**Comment by LinguList** [comment]
When doing so, one could add the DOI of the paper for completeness to the reference in metadata.json.

**Comment by SimonGreenhill** [comment]
Done here: https://github.com/lexibank/oskolskayatungusic/commit/24184ab5f5227428858b1c4db62122ada1305161
